# Generated by Django 3.2.2 on 2021-05-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="team",
            name="csr",
        ),
        migrations.RemoveField(
            model_name="team",
            name="public_key",
        ),
        migrations.RemoveField(
            model_name="team",
            name="status",
        ),
        migrations.CreateModel(
            name="TeamCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField()),
                ("csr", models.TextField()),
                ("certificate", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("waiting for certificate", "waiting for certificate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamACMEAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField()),
                ("email", models.CharField(max_length=255)),
                ("private_key", models.TextField()),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acme_account",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
