# Generated by Django 3.2.2 on 2021-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_auto_20210508_1344"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamcertificate",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="teamcertificate",
            name="valid_until",
        ),
        migrations.AlterField(
            model_name="teamcertificate",
            name="certificate",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="teamcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("waiting for certificate", "waiting for certificate"),
                ],
                default="waiting for certificate",
                max_length=30,
            ),
        ),
    ]
