# Generated by Django 3.2.2 on 2021-05-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_auto_20210508_1624"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamACMEAccount",
        ),
    ]
