# Generated by Django 3.2.2 on 2021-05-09 12:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_delete_teamacmeaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
        ),
    ]
