# Generated by Django 3.1.4 on 2020-12-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturekey",
            name="active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
