# Generated by Django 3.1.4 on 2020-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formsubmission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='description',
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
