# Generated by Django 3.1.4 on 2021-01-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forms", "0007_signaturekey_subkey_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="teams",
            field=models.ManyToManyField(related_name="forms", to="auth.Group"),
        ),
    ]
