# Generated by Django 3.2 on 2021-05-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0013_auto_20210501_1153"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="public_key",
            field=models.TextField(default="dd"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="forms.team",
            ),
        ),
    ]
