# Generated by Django 3.2 on 2021-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_auto_20210501_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin")], max_length=9
            ),
        ),
    ]
