# Generated by Django 3.2 on 2021-05-02 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0015_alter_teammembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptionkey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="certificate",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="csr",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("waiting for certificate", "waiting for certificate"),
                ],
                default="active",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
