# Generated by Django 3.2.2 on 2021-05-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("forms", "0016_auto_20210502_1300"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammembership",
            name="team",
        ),
        migrations.RemoveField(
            model_name="teammembership",
            name="user",
        ),
        migrations.AlterField(
            model_name="form",
            name="teams",
            field=models.ManyToManyField(related_name="forms", to="teams.Team"),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamMembership",
        ),
    ]
